export default [
    'CSN',
    'Localiza',
    'Bradespar',
    'Petrobras',
    'Weg',
    'Usiminas',
    'Sabesp',
    'IRB Brasil',
    'Klabin SA',
    'TIM Participações',
    'Cemig',
    'Carrefour',
    'Telefônica Brasil',
    'Ambev SA',
    'Estacio Part',
    'Bradesco',
    'Qualicorp',
    'Engie',
    'Ecorodovias',
    'Viavarejo',
    'Suzano Papel',
    'Gerdau Met',
    'Petrobras',
    'Cogna',
    'Hypera',
    'Sul América',
    'Eletrobras',
    'Multiplan',
    'BTGP Banco',
    'B2W Digital',
    'Hapvida',
    'Petrobras Distribuidora',
    'BR Malls',
    'Gerdau',
    'RaiaDrogasil',
    'Santander BR',
    'Vale',
    'Embraer',
    'Cosan',
    'Braskem',
    'CPFL Energia',
    'BB Seguridade',
    'Notre Dame Part',
    'Cyrela',
    'Lojas Americanas',
    'Iguatemi',
    'BRF SA',
    'Cielo',
    'Pão de Açúcar',
    'Fleury',
    'Equatorial Energia',
    'AZUL',
    'Itaúsa',
    'Itaú Unibanco',
    'Eletrobras',
    'Rumo Log',
    'Grupo Natura',
    'B3',
    'JBS Friboi',
    'Bradesco',
    'Taesa',
    'Minerva',
    'Energias BR',
    'Banco do Brasil',
    'CVC Brasil',
    'Magazine Luiza',
    'CCR',
    'MRV Engenharia',
    'Gol',
    'Lojas Renner',
    'Cia Hering'
  ];